// <auto-generated />
using System;
using InfoFretamento.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfoFretamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241219222026_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrigemPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("date");

                    b.Property<int>("ViagemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimamal(18,2)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRealizada")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<int>("KmAtual")
                        .HasColumnType("integer");

                    b.Property<int>("KmPrevista")
                        .HasColumnType("integer");

                    b.Property<int>("KmRealizada")
                        .HasColumnType("integer");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Passagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("PassageiroId")
                        .HasColumnType("integer");

                    b.Property<int>("Poltrona")
                        .HasColumnType("integer");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PassageiroId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .IsFixedLength();

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator().HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrigemPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("date");

                    b.Property<int>("ViagemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadeTank")
                        .HasColumnType("integer");

                    b.Property<string>("Carroceria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("KmAtual")
                        .HasColumnType("integer");

                    b.Property<string>("LocalEmplacado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("QuantidadePoltronas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Itinerario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer");

                    b.Property<int>("Parcelas")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoViagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorContratado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDespesas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.ViagemProgramada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FormaPagto")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Guia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Itinerario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorPassagem")
                        .HasColumnType("numeric");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("ViagensProgramadas");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("InfoFretamento.Domain.Entities.Pessoa");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Pessoa", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Cliente_Tipo");
                        });

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Colaborador", b =>
                {
                    b.HasBaseType("InfoFretamento.Domain.Entities.Pessoa");

                    b.HasDiscriminator().HasValue("Colaborador");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Fornecedor", b =>
                {
                    b.HasBaseType("InfoFretamento.Domain.Entities.Pessoa");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Fornecedor");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Motorista", b =>
                {
                    b.HasBaseType("InfoFretamento.Domain.Entities.Pessoa");

                    b.HasDiscriminator().HasValue("Motorista");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Passageiro", b =>
                {
                    b.HasBaseType("InfoFretamento.Domain.Entities.Pessoa");

                    b.Property<string>("Cartao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("Passageiro");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("InfoFretamento.Domain.Entities.Cliente", null)
                        .WithMany("Despesas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("InfoFretamento.Domain.Entities.Fornecedor", null)
                        .WithMany("Despesas")
                        .HasForeignKey("FornecedorId");

                    b.HasOne("InfoFretamento.Domain.Entities.Motorista", null)
                        .WithMany("Despesas")
                        .HasForeignKey("MotoristaId");

                    b.HasOne("InfoFretamento.Domain.Entities.Pessoa", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Veiculo", null)
                        .WithMany("Despesas")
                        .HasForeignKey("VeiculoId");

                    b.HasOne("InfoFretamento.Domain.Entities.Viagem", "Viagem")
                        .WithMany("Despesas")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Manutencao", b =>
                {
                    b.HasOne("InfoFretamento.Domain.Entities.Servico", "Servico")
                        .WithMany("Manutencoes")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Manutencoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Passagem", b =>
                {
                    b.HasOne("InfoFretamento.Domain.Entities.Passageiro", "Passageiro")
                        .WithMany("Passagens")
                        .HasForeignKey("PassageiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.ViagemProgramada", "Viagem")
                        .WithMany("Passagens")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passageiro");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Pessoa", b =>
                {
                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.DocumentoCliente", "Documento", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("integer");

                            b1.Property<string>("Documento")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoa");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("integer");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoa");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Receita", b =>
                {
                    b.HasOne("InfoFretamento.Domain.Entities.Cliente", null)
                        .WithMany("Receitas")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Fornecedor", null)
                        .WithMany("Receitas")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Motorista", null)
                        .WithMany("Receitas")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Pessoa", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Viagem", "Viagem")
                        .WithMany("Receitas")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Viagem", b =>
                {
                    b.HasOne("InfoFretamento.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Viagens")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Motorista", "Motorista")
                        .WithMany("Viagens")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoFretamento.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Viagens")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Horario", "DataHorarioChegada", b1 =>
                        {
                            b1.Property<int>("ViagemId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("ViagemId");

                            b1.ToTable("Viagens");

                            b1.WithOwner()
                                .HasForeignKey("ViagemId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Horario", "DataHorarioRetorno", b1 =>
                        {
                            b1.Property<int>("ViagemId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("ViagemId");

                            b1.ToTable("Viagens");

                            b1.WithOwner()
                                .HasForeignKey("ViagemId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Horario", "DataHorarioSaida", b1 =>
                        {
                            b1.Property<int>("ViagemId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("ViagemId");

                            b1.ToTable("Viagens");

                            b1.WithOwner()
                                .HasForeignKey("ViagemId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Horario", "DataHorarioSaidaGaragem", b1 =>
                        {
                            b1.Property<int>("ViagemId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.HasKey("ViagemId");

                            b1.ToTable("Viagens");

                            b1.WithOwner()
                                .HasForeignKey("ViagemId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Rota", "Rota", b1 =>
                        {
                            b1.Property<int>("ViagemId")
                                .HasColumnType("integer");

                            b1.HasKey("ViagemId");

                            b1.ToTable("Viagens");

                            b1.WithOwner()
                                .HasForeignKey("ViagemId");

                            b1.OwnsOne("InfoFretamento.Domain.ValueObjects.Local", "Retorno", b2 =>
                                {
                                    b2.Property<int>("RotaViagemId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("CidadeSaida")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("LocalDeSaida")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("UfSaida")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)");

                                    b2.HasKey("RotaViagemId");

                                    b2.ToTable("Viagens");

                                    b2.WithOwner()
                                        .HasForeignKey("RotaViagemId");
                                });

                            b1.OwnsOne("InfoFretamento.Domain.ValueObjects.Local", "Saida", b2 =>
                                {
                                    b2.Property<int>("RotaViagemId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("CidadeSaida")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("LocalDeSaida")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("UfSaida")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)");

                                    b2.HasKey("RotaViagemId");

                                    b2.ToTable("Viagens");

                                    b2.WithOwner()
                                        .HasForeignKey("RotaViagemId");
                                });

                            b1.Navigation("Retorno")
                                .IsRequired();

                            b1.Navigation("Saida")
                                .IsRequired();
                        });

                    b.Navigation("Cliente");

                    b.Navigation("DataHorarioChegada")
                        .IsRequired();

                    b.Navigation("DataHorarioRetorno")
                        .IsRequired();

                    b.Navigation("DataHorarioSaida")
                        .IsRequired();

                    b.Navigation("DataHorarioSaidaGaragem")
                        .IsRequired();

                    b.Navigation("Motorista");

                    b.Navigation("Rota")
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.ViagemProgramada", b =>
                {
                    b.HasOne("InfoFretamento.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("ViagensProgramadaas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.HorarioLocal", "Chegada", b1 =>
                        {
                            b1.Property<int>("ViagemProgramadaId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Local")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ViagemProgramadaId");

                            b1.ToTable("ViagensProgramadas");

                            b1.WithOwner()
                                .HasForeignKey("ViagemProgramadaId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.HorarioLocal", "Retorno", b1 =>
                        {
                            b1.Property<int>("ViagemProgramadaId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Local")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ViagemProgramadaId");

                            b1.ToTable("ViagensProgramadas");

                            b1.WithOwner()
                                .HasForeignKey("ViagemProgramadaId");
                        });

                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.HorarioLocal", "Saida", b1 =>
                        {
                            b1.Property<int>("ViagemProgramadaId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Hora")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Local")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ViagemProgramadaId");

                            b1.ToTable("ViagensProgramadas");

                            b1.WithOwner()
                                .HasForeignKey("ViagemProgramadaId");
                        });

                    b.Navigation("Chegada")
                        .IsRequired();

                    b.Navigation("Retorno")
                        .IsRequired();

                    b.Navigation("Saida")
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Motorista", b =>
                {
                    b.OwnsOne("InfoFretamento.Domain.ValueObjects.Habilitacao", "Habilitacao", b1 =>
                        {
                            b1.Property<int>("MotoristaId")
                                .HasColumnType("integer");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Protocolo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateOnly>("Vencimento")
                                .HasColumnType("date");

                            b1.HasKey("MotoristaId");

                            b1.ToTable("Pessoa");

                            b1.WithOwner()
                                .HasForeignKey("MotoristaId");
                        });

                    b.Navigation("Habilitacao")
                        .IsRequired();
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Manutencoes");

                    b.Navigation("Viagens");

                    b.Navigation("ViagensProgramadaas");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Viagem", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.ViagemProgramada", b =>
                {
                    b.Navigation("Passagens");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Motorista", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("InfoFretamento.Domain.Entities.Passageiro", b =>
                {
                    b.Navigation("Passagens");
                });
#pragma warning restore 612, 618
        }
    }
}
